version: '3'
 
services:
  app:
    container_name: ${APP_NAME}
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    environment:
      PHP_EXTRA_CONFIGURE_ARGS: --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data
      HOSTNAME: ${APP_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PROJECT_NAME: ${PROJECT_NAME}
    ports:
      - ${APP_PORT}:9000
    volumes:
      - ./${PROJECT_NAME}:/var/www/html/${PROJECT_NAME}/
    working_dir: /var/www/html/${PROJECT_NAME}/
    links:
      - mysql

  nginx:
    container_name: ${NGINX_NAME}
    image: nginx:1.13.8
    ports:
      - ${NGINX_PORT}:80
    environment:
      HOSTNAME: ${NGINX_NAME}
      PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      - ./${PROJECT_NAME}:/var/www/html/${PROJECT_NAME}
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  mysql:
    container_name: ${MYSQL_NAME}
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: mysql-app:latest
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}